@startuml
title Kuvu(Dating) App Authentication Flow

actor User
participant "UserInterface\n(Flutter)" as UserInterface #LightBlue
participant "AuthService\n(Flutter)" as AuthService #LightBlue
participant FirebaseAuth
participant "AuthController\n(Backend)" as AuthController #LightGreen
participant "AuthMiddleware\n(Backend)" as AuthMiddleware #LightGreen
participant "UserService\n(Backend)" as UserService #LightGreen
participant "Database\n(MongoDB)" as Database #LightGreen

User -> UserInterface: SignIn
UserInterface -> AuthService: signInWithFacebook() / signInWithApple()
AuthService -> FirebaseAuth: authenticateWithFirebase(providerToken)
FirebaseAuth -> AuthService: idToken
AuthService -> UserInterface: idToken
UserInterface -> AuthController: sendIdTokenToBackend(idToken)
AuthController -> AuthMiddleware: authenticateToken(idToken)
AuthMiddleware -> FirebaseAuth: verifyIdToken(idToken)
FirebaseAuth -> AuthMiddleware: decodedToken
AuthMiddleware -> UserService: getUserDetails(decodedToken)
UserService -> Database: retrieveUserData(userId)
Database -> UserService: userDetails
UserService -> AuthController: userDetails
AuthController -> UserInterface: userDetails
UserInterface -> User: displayProfile(userDetails)
@enduml
